#!/bin/sh

set -e

host=$(env | grep _TCP_ADDR | head -1 | cut -d = -f 2)
port=$(env | grep _TCP_PORT | head -1 | cut -d = -f 2)

# assuming a timeout of 30 second should be enough for a container ?
TIMEOUT=30

echo -n "waiting for TCP connection to $host:$port ..."
COUNTER=0
while ! nc -w 1 $host $port 2>/dev/null
do
    if [[ $COUNTER -lt $TIMEOUT ]]; then
        echo -n .
        sleep 1
        COUNTER=$((COUNTER+1))
    else
        echo "No TCP connection received on $host:$port "
        break
    fi
done

if [[ $COUNTER -lt $TIMEOUT ]]; then
    echo " OK"
fi
