---
name: 'lint'

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  hadolint:
    name: hadolint
    runs-on: ubuntu-20.04
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Run hadolint
        uses: hadolint/hadolint-action@c27bd9edc1e95eed30474db8f295ff5807ebca14
        # v1.5.0 => c27bd9edc1e95eed30474db8f295ff5807ebca14

  markdown-lint:
    name: markdown-lint
    runs-on: ubuntu-20.04
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Run markdown-lint
        uses: avto-dev/markdown-lint@04d43ee9191307b50935a753da3b775ab695eceb
        # v1.5.0 => 04d43ee9191307b50935a753da3b775ab695eceb
        with:
          config: '.github/linters/.markdown-lint.yml'
          args: './README.md'

  shellcheck:
    name: shellcheck
    runs-on: ubuntu-20.04
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@94e0aab03ca135d11a35e5bfc14e6746dc56e7e9
        # 1.1.0 => 94e0aab03ca135d11a35e5bfc14e6746dc56e7e9
        env:
          SHELLCHECK_OPTS: -s bash
  shfmt:
    name: shfmt
    runs-on: ubuntu-20.04
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Run shfmt
        uses: luizm/action-sh-checker@7f44869033b40ee4ffe7dc76c87a1bc66e3d025a
        # v0.3.0 => 7f44869033b40ee4ffe7dc76c87a1bc66e3d025a
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          SHFMT_OPTS: -l -d -i 2
        with:
          sh_checker_shellcheck_disable: true
          sh_checker_comment: true

  yamllint:
    name: yamllint
    runs-on: ubuntu-20.04
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@c19bd0523a9011c3a3960fe6640a0882b59af15d
        # v3.0.2 => c19bd0523a9011c3a3960fe6640a0882b59af15d
        with:
          config_file: '.github/linters/.yamllint.yml'
